[package]
name = "cached-run"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Stores and resuses the result of a command."
categories = "command-line-utilities"

[dependencies]
dirs = "4.0"
atty = "0.2"
